### ISSUE TITLE
Discussion and Suggestions

### ISSUE THREAD

**Issue by adi-g15** [adi-g15/worldLineSim#1]
Please put down your suggestion in this issue, i will be thankful to you for having you let me know some more interesting thing, or a knowledgable advice 😄 .

Also, if you think some though is good to be put here, you can put your thoughts here, I would be happy to know more.

**Comment by hhfdserth** [comment]
Keep in mind I have less then 2 months experience on a laptop. I dont know shit about how anything works. Im pushing random buttons and clicking on things looking for some result. Do your thing and I will try to keep up.

**Comment by adi-g15** [comment]
This issue will be closed in favour of the discussions tabs available now. Thanks @hhfdserth for replying in this 🔢
